package com.example.resourses.theme

const val ProductsList = "Список товаров"
const val SearchHint = "Поиск товаров"
const val InStorehouse = "На складе"
const val AppendingDate = "Дата добавления"
const val OutOfStock = "Нет в наличии"
const val SomethingGoingWrong = "Что-то пошло не так..."
const val MeanIt = "Понятно"
const val ProductAmount = "Количество товара"
const val ProductDeletion = "Удаление товара"
const val ConfirmationQuestion = "Вы действительно хотите удалить выбранный товар?"
const val CancelCaption = "Отмена"
const val AcceptCaption = "Принять"
const val NoCaption = "Нет"
const val YesCaption = "Да"
const val EmptyResultBySearchRequest = "К сожалению не найдены товары, соответствующие Вашему запросу"
const val EmptyStock = "К сожалению в данный момент на нашем складе отсутствуют какие-либо товары"